
/*
    ----- Generated by Claude - Sonnet 4.6 -----
*/

#pragma once

#include <unordered_map>
#include <vector>
#include <cassert>
#include <algorithm>

#include "scene/Entity.h"

#include "MeshRenderer.h"
#include "MeshFilter.h"
#include "Transform.h"
#include "SkeletonComponent.h"
#include "AnimatonComponent.h"
#include "ColliderComponent.h"
#include "ControllerComponent.h"
#include "MovementComponent.h"
#include "RigidBodyComponent.h"
#include "NameTagComponent.h"
#include "CameraComponent.h"
#include "Hierarchy.h"
#include "Light.h"


namespace Lengine {

    template<typename T>
    class ComponentStorage
    {
    public:
        // ---------------------------------------------------------
        // Add a component to an entity.
        // If it already exists, overwrites it.
        // ---------------------------------------------------------
        T& Add(const Entity& entityID, const T& component = T())
        {
            // If already has it, just update in-place
            if (Has(entityID))
            {
                uint32_t idx = m_Sparse[entityID];
                m_Dense[idx] = component;
                return m_Dense[idx];
            }

            // Grow sparse array if needed
            if (entityID >= m_Sparse.size())
                m_Sparse.resize(entityID + 1, INVALID);

            // Record where in the dense array this entity lives
            m_Sparse[entityID] = static_cast<uint32_t>(m_Dense.size());

            // Append to dense arrays
            m_Dense.push_back(component);
            m_DenseEntities.push_back(entityID);

            return m_Dense.back();
        }

        // ---------------------------------------------------------
        // Remove by swapping with the last element (keeps dense
        // array packed with no gaps).
        // ---------------------------------------------------------
        void Remove(const Entity& entityID)
        {
            if (!Has(entityID))
                return;

            uint32_t removedIdx = m_Sparse[entityID];
            uint32_t lastIdx = static_cast<uint32_t>(m_Dense.size()) - 1;

            if (removedIdx != lastIdx)
            {
                // Move last element into the removed slot
                m_Dense[removedIdx] = std::move(m_Dense[lastIdx]);
                m_DenseEntities[removedIdx] = m_DenseEntities[lastIdx];

                // Update sparse so the moved entity now points to its new slot
                Entity movedEntity = m_DenseEntities[removedIdx];
                m_Sparse[movedEntity] = removedIdx;
            }

            // Pop the now-duplicate last element
            m_Dense.pop_back();
            m_DenseEntities.pop_back();

            // Invalidate the removed entity's sparse entry
            m_Sparse[entityID] = INVALID;
        }

        // ---------------------------------------------------------
        // O(1) existence check — just an array index + sentinel
        // compare, no hashing at all.
        // ---------------------------------------------------------
        bool Has(const Entity& entityID) const
        {
            return entityID < m_Sparse.size()
                && m_Sparse[entityID] != INVALID;
        }

        T& Get(const Entity& entityID)
        {
            assert(Has(entityID) && "Entity does not have this component");
            return m_Dense[m_Sparse[entityID]];
        }

        const T& Get(const Entity& entityID) const
        {
            assert(Has(entityID) && "Entity does not have this component");
            return m_Dense[m_Sparse[entityID]];
        }

        // ---------------------------------------------------------
        // Direct access to the packed array — this is what systems
        // iterate. It's a plain contiguous vector<T>, nothing else.
        // ---------------------------------------------------------
        std::vector<T>& GetDense() { return m_Dense; }
        const std::vector<T>& GetDense() const { return m_Dense; }

        // Which entity owns dense[i]
        const std::vector<Entity>& GetEntities() const { return m_DenseEntities; }

        // Size = number of components currently alive
        size_t Size() const { return m_Dense.size(); }
        bool   Empty() const { return m_Dense.empty(); }

        void Clear()
        {
            m_Dense.clear();
            m_DenseEntities.clear();
            m_Sparse.clear();
        }


        // ---------------------------------------------------------
        // Clone into a new registry (used for scene duplication).
        // entityMap maps old entity IDs → new entity IDs.
        // ---------------------------------------------------------
        void CloneFrom(
            const ComponentStorage<T>& src,
            const std::unordered_map<Entity, Entity>& entityMap)
        {
            Clear();
            for (size_t i = 0; i < src.m_Dense.size(); ++i)
            {
                Entity oldEntity = src.m_DenseEntities[i];
                auto   it = entityMap.find(oldEntity);
                if (it == entityMap.end())
                    continue;
                Add(it->second, src.m_Dense[i]);
            }
        }

    private:
        static constexpr uint32_t INVALID = std::numeric_limits<uint32_t>::max();

        // Dense packed arrays — these are what the CPU loves
        std::vector<T>      m_Dense;          // component data, tightly packed
        std::vector<Entity> m_DenseEntities;  // entity[i] owns Dense[i]

        // Sparse index: m_Sparse[entityID] = index into m_Dense
        // Size grows to fit the largest entity ID seen
        std::vector<uint32_t> m_Sparse;
    };

} // namespace Lengine